ARG BASE_IMAGE_VERSION
FROM geonode/geoserver:${BASE_IMAGE_VERSION}

# ENV GEOSERVER_DATA_DIR="/geoserver_data/data"

# VOLUME $GEOSERVER_DATA_DIR
# ENTRYPOINT [ "/usr/local/tomcat/tmp/entrypoint.sh" ]
