# Generated by Django 4.2.9 on 2024-10-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PermissionsModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "permissions": (("can_trigger_inference", "Can Trigger AI Inference"),),
                "managed": False,
            },
        ),
    ]
