# Generated by Django 4.2.9 on 2025-01-29 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0034_auto_20200512_1431"),
        ("base", "0092_migrate and_remove_resourcebase_files"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("litterassessment", "0002_add_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inference",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("ended", models.DateTimeField(blank=True, null=True)),
                ("details", models.TextField(blank=True)),
                ("job_url", models.URLField(blank=True)),
                ("payload", models.JSONField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("RUNNING", "running"),
                            ("FAILED", "failed"),
                            ("CANCELLED", "cacelled"),
                            ("COMPLETE", "complete"),
                            ("DELETED", "deleted"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_group",
                        to="groups.groupprofile",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_resource",
                        to="base.resourcebase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoked AI Inference",
            },
        ),
    ]
